### PR TITLE
ufraw-gimp: properly send EXIF data to Gimp 2.9 and later

### PR DESCRIPTION
**Pull request by mardy**
This is the fix for the first issue mentioned in #8

### CODE REVIEW

**Comment by mardy** [comment]
I pushed one more commit to fix the other issue, too :-)

**Review by sergiomb2 — COMMENTED** [review]
and in https://github.com/sergiomb2/ufraw/blob/75c39931ead5207cff514c90d3a77b48be11d466/ufraw-gimp.c#L494 it correct ?

**Comment by mardy** [comment]
> and in
> 
> https://github.com/sergiomb2/ufraw/blob/75c39931ead5207cff514c90d3a77b48be11d466/ufraw-gimp.c#L494
> 
> it correct ?

I'm not sure I understand the question, but I guess that the line that you link to is for versions even older than 2.8. That code will not be used for gimp > 2.9

**Comment by sergiomb2** [comment]
ah, OK,  so GIMP_CHECK_VERSION(2,8,0) means gimp >= 2.8.0 ? 

Thank you

**Comment by mardy** [comment]
> ah, OK, so GIMP_CHECK_VERSION(2,8,0) means gimp >= 2.8.0 ?

Yes:
```
#define GIMP_CHECK_VERSION(major, minor, micro) \
    (GIMP_MAJOR_VERSION > (major) || \
     (GIMP_MAJOR_VERSION == (major) && GIMP_MINOR_VERSION > (minor)) || \
     (GIMP_MAJOR_VERSION == (major) && GIMP_MINOR_VERSION == (minor) && \
      GIMP_MICRO_VERSION >= (micro)))
```

**Pull request merged**
